"""add file upload in messages

Revision ID: e32aced3c78c
Revises: d76700841f3f
Create Date: 2025-11-22 16:50:10.731733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32aced3c78c'
down_revision: Union[str, None] = 'd76700841f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('file_url', sa.String(length=500), nullable=True))
    op.add_column('chat_messages', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('chat_messages', sa.Column('file_type', sa.String(length=100), nullable=True))
    op.add_column('chat_messages', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'file_size')
    op.drop_column('chat_messages', 'file_type')
    op.drop_column('chat_messages', 'file_name')
    op.drop_column('chat_messages', 'file_url')
    # ### end Alembic commands ###
