"""add reminder_sent column

Revision ID: e26df92e3880
Revises: e32aced3c78c
Create Date: 2025-12-06 20:13:53.982217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26df92e3880'
down_revision: Union[str, None] = 'e32aced3c78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('appointments', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute('UPDATE appointments SET reminder_sent = FALSE WHERE reminder_sent IS NULL')
    # Now make it NOT NULL
    op.alter_column('appointments', 'reminder_sent', nullable=False, server_default=sa.false())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'reminder_sent')
    # ### end Alembic commands ###
